version: '3.7'
services:
  nfd-app:
    image: 'dottjt/nfd-app'
    container_name: 'nfd-app'
    env_file:
      - .env
    ports:
      - 4000:4000
    build:
      context: .
    depends_on:
      - nfd-db

  nfd-db:
    image: postgres:11.2-alpine
    container_name: nfd-db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    # external: true

