networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container

services:
  web:
    image: "myapp:latest"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    env_file:
      - config/docker.env
    networks:
      - webnet
      
  db:
    image: postgres:10-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - config/docker.env
    networks:
      - webnet
