version: '3.3'
services:
  nfd-app:
    image: 'dottjt/nfd-app'
    container_name: 'nfd-app'
    # NOTE: env files are for when testing on local, on travis it uses travis encrypted variables
    # env_file:
    #   - .env
    ports:
      - 4000:4000    
    build:
      context: .
    # depends_on:
    #   - nfd-db
    networks:
      - nginx-network

  # nfd-db:
  #   image: postgres:11.2-alpine
  #   container_name: nfd-db
  #   # env_file:
  #   #   - .env
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - nginx-network

networks:
  nginx-network:
    driver: bridge

